#!/usr/bin/perl

print "Content-type: text/html\n\n";


# File eh_myhtmlgen1.pl created by Eric Hepperle at 08:37:57 on Fri Aug 17 2001. 
#
# Program:	eh_createtblnapndcells_2.pl
# Creator:	Eric Hepperle
# Date:		08/22/01
#
# Purpose:	Lets user maintain 
#
########################################################
#
# Revisions:
#
#	08/22/01
#	  - R1. This is code borrowed from
#	    my original script I created 08/21/01.
#	  - Added style tags.
#	  - Put a space after the "Time" prompt.
#	  - Set bgcolor permanent.
#	  - Added preformatting tags. (it didn't help)
#	  - Implemented date subroutine to grab convert
#	    date to MMDDYY format.
#	  - Utilized the mmddyy variable to create a
#	    filename referencing the date.
#
#	08/23/01
#	  - Adjusted some font properties
#
#########################################################
#
# Planned Improvements:
#
# *  Make a versions and variations list.
# *  Make a version where the log is one whole table.
# *  Eventually make this a CGI.
#
#########################################################

&time_mmddyy;
print "\n";

#********************************************************
# DEFAULTS:
#********************************************************
#
$maindir = "/afs/rchland.ibm.com/usr3/v2cib484/tmp";
#PC VERSION:  "file:///C:/Windows/Desktop/tmp.dir"
#
$docname = "html_test_doc.html";
#$webfile = "$maindir/$docname";
#$titletext = "This is a test web page generated by my perlscript webpage creator";
$titletext = "EH DAILY LOG:  $dd/$mm/$yy\n";
$bgc = "lightskyblue";
#$bodycontent = "AIX IS AWESOME!!!";


#********************************************************
# DISCLAIMER/HEADER:
#********************************************************
#
print "\n";
print "This program will allow you to enter an updated list of\n";
print "events and to keep a log of your day.\n";
print "\n";
print "\n";



#*********************************************************
# GET INPUT FROM USER:
#*********************************************************
#

#--------------------------------
# Define Temp Table File:
#
$temptablefile = "$maindir/tablefile.tmp";


#-------------------------------
# Define Cumulative Cell File:
#
$templogfile = "$maindir/logfile.tmp";


#---------------------------------
# Get content info:
#
# Get event time:
print "Time: ";
$event_time = <STDIN>;
chomp $event_time;

print "The time will be logged as $event_time.";
print "\n";

# Get event text:
print "Enter what happened:\n";
print "(Press <ctrl + d> when done)\n";
@event_text = <STDIN>;
chomp @event_text;
print "\n";

print "Here is what you just typed:\n";
print @event_text;
print "\n";


#*********************************************************
# FORMAT TABLE:
#*********************************************************

#----------------------------------
# Create New Cell, Do Variable
# substitution, and write to file.
#
$scalartime = localtime(time);

&create_cell;
print "\n";

# initialize file.
open (OUT, ">>$templogfile");

   print OUT "\n";

close (OUT);


&printfile;

open OUT, ">>$templogfile" or die "Cannot open $templogfile for append :$!";

##------------(*)--------------##





print "\n";
print "The following is the contents of \$scalartime: \n";
print $scalartime;
print "\n";
print "\n";


# Keep this as example:
# print OUT 'The time is now : ',scalar(localtime),"\n";

close OUT;

&printfile;


#*********************************************************
# FORMAT & CREATE MAIN WEB PAGE:
#*********************************************************
#

$docname = "eh_dailylog_$mmddyy.html";

print "\n";
print "The webpage created will be called: $docname";
print "\n";	

$webfile = "$maindir/$docname";


&rdfilen2array;

open (HTML_DOC, ">>$webfile") || die "cannot open output file $webfile \n";

print HTML_DOC "<HTML>\n";
print HTML_DOC "\n";
print HTML_DOC "<HEAD>\n";
print HTML_DOC "\n";
print HTML_DOC "<TITLE>\n";
print HTML_DOC "$titletext\n";
print HTML_DOC "</TITLE>\n";
print HTML_DOC "\n";
print HTML_DOC "</HEAD>\n";
print HTML_DOC "\n";
print HTML_DOC "<STYLE>\n";
print HTML_DOC "\n";
print HTML_DOC "\.time \{font-family:  \"Gill Sans\", \"Tahoma\", \"Arial\"\; font-size: 10pt\; color: red\}\n";
print HTML_DOC "\.tiny \{ font-family:  \"Tahoma\",\"Gill Sans\",\"Arial\"\; font-size: 4pt\; color: lightslateblue\}\n";
print HTML_DOC "\.tinyp1 \{ font-family:  \"Tahoma\",\"Gill Sans\",\"Arial\"\; font-size: 5pt\; color: lightslateblue\}\n";
print HTML_DOC "\.tndstamp \{ font-family:  \"Tahoma\",\"Gill Sans\",\"Arial\"\; font-size: 10pt\; color: lightslateblue\}\n";
print HTML_DOC "\.regular \{ font-family:  \"Tahoma\",\"Arial\"\; font-size: 9.5pt\; color: black\}\n";
print HTML_DOC "\n";        
print HTML_DOC "</STYLE>\n";
print HTML_DOC "\n";
print HTML_DOC "<BODY BGCOLOR = $bgc>\n";
print HTML_DOC "\n";
print HTML_DOC "<TABLE BORDER = 2>\n";
print HTML_DOC "\n";
print HTML_DOC @bodycontent;
print HTML_DOC "\n";
print HTML_DOC "</TABLE>\n";
print HTML_DOC "\n";
print HTML_DOC "</BODY>\n";
print HTML_DOC "\n";
print HTML_DOC "</HTML>\n";
print HTML_DOC "\n";


close (HTML_DOC);


#*********************************************************
# VERIFY:
#*********************************************************
#

print "Press Enter to Continue:\n";
$hold = <STDIN>;


if (open (TEMPLOG, "$templogfile")) {

    $line = <Myfile>;

    while ($line ne "") {

	print ($line);

	$line = <Myfile>;

    }

}

print "\n";


 if (open (TEMPTABLE, "$temptablefile")) {

    $line = <Myfile>;

    while ($line ne "") {

	print ($line);

	$line = <Myfile>;

    }

}

print "\n";


 if (open (HTML_DOC, "$webdoc")) {

    $line = <Myfile>;

    while ($line ne "") {

	print ($line);

	$line = <Myfile>;

    }

}


print "\n";

print "\n";
print "\n";
print "\n";

print @event_text;
print "\n";
print "\n";
print "The End!\n";



#***********************************************************
# SUBROUTINES:
#***********************************************************

sub printfile {

        open (IN, $templogfile) || die "Cannot open $templogfile for read :$!";

           while (<IN>) {

           print;

           }

        close IN;
}



sub create_cell {

   open (TEMPLOG, ">$templogfile") || die "cannot open specified file $templogfile \n";

   print TEMPLOG "<!--BEGIN ROW------------>\n";
   print TEMPLOG "\n";
   print TEMPLOG "<TR>\n";
   print TEMPLOG "\n";
   print TEMPLOG "   <TD WIDTH = 70 VALIGN = TOP><H6 CLASS = \"time\">$event_time</H6>\n";
   print TEMPLOG "   </TD>\n";
   print TEMPLOG "\n";
   print TEMPLOG "   <TD WIDTH = 450 VALIGN = TOP>";
   print TEMPLOG "<P><H6 CLASS = \"tndstamp\">$scalartime</H6></P>"; 
   print TEMPLOG "\n";
   print TEMPLOG "<FONT SIZE = 2 CLASS = \"regular\">@event_text</FONT>";
   print TEMPLOG "\n";
   print TEMPLOG "   </TD>\n";
   print TEMPLOG "\n";
   print TEMPLOG "</TR>\n";
   print TEMPLOG "\n";

close (TEMPLOG);

}


sub create_table {

@eventinfo = (<TEMPLOG>);
print "\n";
print "\n";
print "Here is contents of \"Templog\" file: \n";
print (@eventinfo);


open (TEMPTABLE, ">$temptablefile") || die "cannot open specified file $temptablefile \n";

   # erase previous contents.
   print TEMPTABLE "\n";

   print TEMPTABLE "<TABLE>\n";

   print TEMPTABLE (@event);

   print TEMPTABLE "</TABLE>\n";

close (TEMPTABLE);

}



sub rdfilen2array {

   unless (open (CUMFILE, "$templogfile") ) {

      die ("cannot open input file $templogfile \n");

   }

   @bodycontent = <CUMFILE>;

   print (@bodycontent);

}


sub time_mmddyy {

 ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
  $yyyymmdd = sprintf("%04d%02d%02d",$year+1900,$mon+1,$mday);
  $mmddyy = sprintf("%02d%02d%02d",$mon+1,$mday,$year%100);
  print "The date in yyyymmdd format: $yyyymmdd\n";
  print "The date in mmddyy format:   $mmddyy\n";

}


